name: bioskop_app
description: A simple bioskop booking app (dummy data)
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.0
  http: ^0.13.5
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  google_fonts: ^4.0.4
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  file_picker: ^10.3.7
  image_picker_for_web: ^3.0.1
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  file_picker: ^10.3.7